### PR TITLE
Arif khalid fix pe dry run issues

### LINKED ISSUE #131: [PE-D][Tester A] cannot detect some wrong dates
-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: avielcx/ped#6

### LINKED ISSUE #174: [PE-D][Tester E] Error in calculation - follow up
Unable to withdraw the supposed balance

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: raydent30/ped#5

### PR DESCRIPTION
**Pull request by Arif-Khalid**
# Description

## Type of Change

- [ ] Possible breaking change (Change in feature that may cause existing features to not work correctly, e.g. change in
  schema)
- [x] Non breaking change (Bug fix, New feature)

## What type of PR is this?

- [x] bug fix
- [ ] cleanup
- [ ] documentation
- [ ] feature

## What this PR does / Why we need it:

```docs
Fixes the issue of too precise amounts being passed in by the user
Fixes the issue of some dates being invalid but treated as valid
```

## Which issue(s) this PR fixes, if:

Fixes #131 
Fixes #174 

#### Additional documentation e.g., usage docs, testing docs etc.:

```docs

```

## Checklist

- [x] Changes have been tested
- [x] All automated tests pass
- [x] Relevant Tags and Milestones have been added

### CODE REVIEW

File: src/main/java/seedu/duke/TransactionManager.java [hunk 1]
```diff
@@ -253,6 +255,64 @@ public String getAllTransactionsOfMonth (String monthString) throws NoTransactio
...
+        Month month = date.getMonth();
+        int day;
+        try {
+            day = Integer.parseInt(dateString.substring(0, 2));
+        } catch (NumberFormatException e) {
+            assert false;
+            return false;
+        }
+
+        switch (month) {
```
Comment (jacob-stein1) [inline src/main/java/seedu/duke/TransactionManager.java:278]: Hello, it may be good to use an array to store days in each month just to improve readability:

```java
int[] daysInMonth = {31, date.isLeapYear() ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

File: src/main/java/seedu/duke/commands/AddCommand.java [hunk 2]
```diff
@@ -38,28 +39,32 @@ private Currency getCurrency (String currencyString) {
...
 
-        this.amount = new BigDecimal(words[2]);
-        if (this.amount.compareTo(BigDecimal.valueOf(0.01)) < 0) {
+        amount = new BigDecimal(words[2]);
+        if (amount.compareTo(BigDecimal.valueOf(0.01)) < 0) {
             throw new InvalidAmountToAddException();
         }
+        if (getNumberOfDecimalPlaces(amount) > 2) {
+            throw new AmountTooPreciseException();
+        }
```
Comment (jacob-stein1) [inline src/main/java/seedu/duke/commands/AddCommand.java:57]: Great that you are adding this, I also added similar checks in show-rate. When this is merged I can standardize my checks to use AmountTooPrecise exceptions.

File: src/main/java/seedu/duke/commands/ExchangeCommand.java [hunk 3]
```diff
@@ -49,6 +50,9 @@ public void execute (Ui ui, AccountList accounts) {
             if (convertedAmount.compareTo(comparator) < 0) {
                 throw new ExchangeAmountTooSmallException();
             }
+            if (getNumberOfDecimalPlaces(amount) > 2) {
+                throw new AmountTooPreciseException();
+            }
```
Comment (jacob-stein1) [inline src/main/java/seedu/duke/commands/ExchangeCommand.java:55]: Thank you for adding this to exchange. I added max and min values to avoid implicit truncation from Java, but this should solve some precision issues I was having where 0.099 would round to 0.10 for example.

File: src/main/java/seedu/duke/constants/ErrorMessage.java [hunk 4]
```diff
@@ -5,7 +5,8 @@
  */
 public interface ErrorMessage {
     String INVALID_ADD_COMMAND = "Please check that you have correctly provided the currency and amount";
-    String INVALID_AMOUNT_TO_ADD_OR_WITHDRAW = "Please provide a value greater than or equal to 0.01";
+    String INVALID_TOO_SMALL_AMOUNT_TO_ADD_OR_WITHDRAW = "Please provide a value greater than or equal to 0.01";
```
Comment (jacob-stein1) [inline src/main/java/seedu/duke/constants/ErrorMessage.java:8]: I added a similar error message for show-rate when the number is outside the range [0.01, 1b]. If mine ends up being merged second I can change to standardize.

**Review by jacob-stein1 — COMMENTED** [review]
Great job, some minor recommendations and some stuff that I will need to standardize, but otherwise LGTM!

File: src/main/java/seedu/duke/TransactionManager.java (hunk 1 above)
Comment (Arif-Khalid) [reply src/main/java/seedu/duke/TransactionManager.java]: Instead replaced the switch-case statements with a much shorter and cleaner implementation using a constant hashmap in date constants, DAYS_IN_MONTH

Comment (jacob-stein1) [reply src/main/java/seedu/duke/TransactionManager.java]: Just looked over it, great change!
