### PR TITLE
Fix bug to only accept amount greater or equal to 0.01

### LINKED ISSUE #105: [Bug] Adding amounts less than 0.01
When adding and withdrawing amounts less than 0.01, there should be an error message displayed instead of the program treating it as if 0.00 was added or withdrawn as shown in the screenshots attached.
image
image

### PR DESCRIPTION
**Pull request by woowenjun99**
# Description

Screenshot 2023-03-29 at 6 39 47 PM

## Type of Change

- [ ] Possible breaking change (Change in feature that may cause existing features to not work correctly, e.g. change in
  schema)
- [X] Non breaking change (Bug fix, New feature)

## What type of PR is this?

- [X] bug fix
- [ ] cleanup
- [ ] documentation
- [ ] feature

## What this PR does / Why we need it:

```docs

```

## Which issue(s) this PR fixes, if:

Fixes #105 

#### Additional documentation e.g., usage docs, testing docs etc.:

```docs

```

## Checklist

- [x] Changes have been tested
- [ ] All automated tests pass
- [ ] Relevant Tags and Milestones have been added

### CODE REVIEW

File: src/main/java/seedu/duke/constants/Message.java [hunk 1]
```diff
@@ -10,6 +10,7 @@ public enum Message {
             + "\t help - show list of commands\n"
             + "\t add CURRENCY AMOUNT - adds that amount of money into that currency account\n"
             + "\t balance [CURRENCY] - view balances of accounts\n"
+            + "\t\t no CURRENCY - displays all currencies\n"
```
Comment (Arif-Khalid) [inline src/main/java/seedu/duke/constants/Message.java]: It would be better to include all the possible use cases and what it does in the sub table. For example
```suggestion
            + "\t\t balance - displays the balances of all accounts\n"
            + "\t\t balance <CURRENCY> - displays the balance of that specific currency account\n"
```

**Review by Arif-Khalid — COMMENTED** [review]
Small change required in help command the bug fix implementation looks good

**Review by Arif-Khalid — APPROVED** [review]
LGTM!
