### PR TITLE
119 program crashes if the json files are corrupted

### LINKED ISSUE #119: Program crashes if the json files are corrupted
If the json files in the data directory are corrupted, for example changing them such that they are not valid JSON, it causes the program to crash.

## Log
```<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2023-03-30T05:57:18.496042Z</date>
  <millis>1680155838496</millis>
  <nanos>42000</nanos>
  <sequence>0</sequence>
  <logger>logger</logger>
  <level>SEVERE</level>
  <class>seedu.duke.Duke</class>
  <method>main</method>
  <thread>1</thread>
  <message>Something went wrong with starting the app</message>
  <exception>
    <message>com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 2 path $[0]</message>
    <frame>
      <class>com.google.gson.Gson</class>
      <method>fromJson</method>
      <line>1236</line>
    </frame>
    <frame>
      <class>com.google.gson.Gson</class>
      <method>fromJson</method>
      <line>1137</line>
    </frame>
    <frame>
      <class>com.google.gson.Gson</class>
      <method>fromJson</method>
      <line>1075</line>
    </frame>
    <frame>
      <class>seedu.duke.storage.Store</class>
      <method>loadAccountsFromStore</method>
      <line>74</line>
    </frame>
    <frame>
      <class>seedu.duke.Duke</class>
      <method>main</method>
      <line>50</line>
    </frame>
  </exception>
</record>
</log>
```

## Suggested Fix
Catch the JsonSyntaxException and EOFException, and create a new empty file.

### LINKED ISSUE #149: [PE-D][Tester C] Exits early when save file is malformed
If either `data/accounts.json` or `data/transactions.json` is malformed, the application fails on startup. Encountering a corrupted save file should show the user a warning message instead

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ltzehan/ped#9

### LINKED ISSUE #172: [PE-D][Tester A] got problem if change any balance to negative
-------------
Labels: `type.FunctionalityBug` `severity.High`
original: avielcx/ped#24

### PR DESCRIPTION
**Pull request by Bawfen**
# Description

Fixes #119
Fixes #149 
Fixes #172 

## Type of Change

- [ ] Possible breaking change (Change in feature that may cause existing features to not work correctly, e.g. change in
  schema)
- [x] Non breaking change (Bug fix, New feature)

## What type of PR is this?

- [x] bug fix
- [x] cleanup
- [x] documentation
- [x] feature

## What this PR does / Why we need it:

```docs
Makes the loading from file much more robust, catching json parse errors as well as invalid and duplicate accounts.
```

## Which issue(s) this PR fixes, if:

Fixes #119
Fixes #149 
Fixes #172 

#### Additional documentation e.g., usage docs, testing docs etc.:

```docs

```

## Checklist

- [x] Changes have been tested
- [x] All automated tests pass
- [x] Relevant Tags and Milestones have been added

### CODE REVIEW

File: src/main/java/seedu/duke/storage/Store.java [hunk 1]
```diff
@@ -67,20 +83,42 @@ private void createFileIfNotExist (String fullPath) throws IOException {
...
+                if (value > Account.UPPER_BOUND) {
+                    ui.printMessage(ErrorMessage.ACCOUNT_BALANCE_TOO_LARGE_WHEN_LOADING);
+                    value = (float) Account.UPPER_BOUND;
+                }
+                accounts.addAccount(currency, value);
+            } catch (AccountAlreadyExistsException e) {
+                logger.log(Level.WARNING,
+                        "Skipping duplicate account " + currency + " with value " + value + " found in store");
+                ui.printf(ErrorMessage.DUPLICATE_ACCOUNT_WHEN_LOADING, currency);
+            }
```
Comment (jacob-stein1) [inline src/main/java/seedu/duke/storage/Store.java:116]: All of these checks exist within the Validator class. Might it be possible to run the parsed account value through the validator class? You also do not account for checking for non-numeric value, which could be an issue. Either way, great implementation as is, use the validator if you feel it is necessary. Great job!

**Review by jacob-stein1 — COMMENTED** [review]
Great job cleaning up all the small issues. I left a comment regarding using the validator for checking parsed amount balances. Otherwise, LGTM!

File: src/main/java/seedu/duke/storage/Store.java (hunk 1 above)
Comment (Bawfen) [reply src/main/java/seedu/duke/storage/Store.java]: Thank you for bringing up the point on non-numeric values! After some consideration, I have decided not to use the Validator here for 2 reasons. 
1. I need to implement custom logic for both potential errors, either setting the balance to 10 million if it is too large or 0 if it is negative. The validator throws the same exception with different error messages, and working around it would probably lead to some janky logic. 
2. The gson parser already handles the potential non-numeric cases by throwing a parse error. We currently handle that by wiping the file as it is deemed an "irrecoverable" error. We also avoid precision errors as we store the balances as integers instead of floats, so it cannot be edited to have more than 3 decimal places.
